name: meread
description: MeRead
publish_to: "none"

version: 0.6.1+23

environment:
  sdk: ^3.5.2

dependencies:
  dart_rss: ^3.0.3
  dio: ^5.7.0
  dynamic_color: ^1.7.0
  file_picker: ^8.1.3
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.6.0
  flutter_inappwebview: ^6.1.5
  flutter_localizations:
    sdk: flutter
  flutter_swipe_action_cell: ^3.1.5
  flutter_widget_from_html: ^0.15.2
  get: ^4.6.6
  html: ^0.15.4
  html_main_element: ^2.1.0
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  logger: ^2.4.0
  melos: ^6.2.0
  opml: ^0.4.0
  path_provider: ^2.1.4
  share_plus: ^10.1.1
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/meread.png
    - assets/avatar.png
